package com.stepphantom.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.unit.dp

sealed interface Dest { data object Home:Dest;data object Apps:Dest;data object Health:Dest;data object Diag:Dest;data object Advanced:Dest;data class PkgConfig(val pkg:String):Dest }
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun MainScreen(vm:MainViewModel){var dest by rememberSaveable(stateSaver=androidx.compose.runtime.saveable.Saver(save={when(it){is Dest.PkgConfig->"pkg:${it.pkg}";Dest.Apps->"apps";Dest.Health->"health";Dest.Diag->"diag";Dest.Advanced->"adv";else->"home"}},restore={saved->val s=saved as String;when{ s=="apps"->Dest.Apps;s=="health"->Dest.Health;s=="diag"->Dest.Diag;s=="adv"->Dest.Advanced;s.startsWith("pkg:")->Dest.PkgConfig(s.removePrefix("pkg:"));else->Dest.Home}})){mutableStateOf<Dest>(Dest.Home)};Scaffold(bottomBar={NavigationBar{navItem(dest,Dest.Home,"Inicio","⌂"){dest=it};navItem(dest,Dest.Apps,"Apps","☷"){dest=it};navItem(dest,Dest.Health,"Health","♥"){dest=it};navItem(dest,Dest.Diag,"Diag","ⓘ"){dest=it};navItem(dest,Dest.Advanced,"Ajustes","⚙"){dest=it}}}){pad->Box(Modifier.padding(pad)){when(val d=dest){Dest.Home->HomeScreen(vm);Dest.Apps->AppsScreen(vm){dest=Dest.PkgConfig(it)};Dest.Health->HealthConnectScreen(vm);Dest.Diag->DiagnosticsScreen(vm);Dest.Advanced->AdvancedScreen(vm);is Dest.PkgConfig->PackageConfigScreen(vm,d.pkg){dest=Dest.Apps}}}}}
@Composable private fun RowScope.navItem(current:Dest,target:Dest,label:String,glyph:String,set:(Dest)->Unit){NavigationBarItem(selected=current==target||(current is Dest.PkgConfig&&target==Dest.Apps),onClick={set(target)},icon={Text(glyph,style=MaterialTheme.typography.titleMedium)},label={Text(label)})}
@Composable fun HomeScreen(vm:MainViewModel){val cfg by vm.config.collectAsState();ScrollColumn{Text("StepPhantom",style=MaterialTheme.typography.headlineSmall);Text("Módulo LSPosed / Vector · Android 16 · experimental",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);SectionCard{Text("Apps seleccionadas: ${cfg.packages.size} · con módulo activo: ${cfg.packages.values.count{it.enabled}} ");Text("Ruta implementada: SensorManager. Health Connect: diagnóstico + escritura oficial.",style=MaterialTheme.typography.bodySmall)};WarnCard("También tenés que seleccionar estas apps en el Scope de LSPosed / Vector.");SectionCard{Text("Cómo activar",style=MaterialTheme.typography.titleMedium);listOf("1. Seleccioná la app en Apps y configurala.","2. Abrí LSPosed / Vector.","3. Activá StepPhantom.","4. Marcá la misma app en Scope.","5. Reiniciá el proceso de la app.").forEach{Text(it)}}}}
@Composable fun AdvancedScreen(vm:MainViewModel){val logs by vm.logs.collectAsState();var showExport by rememberSaveable{mutableStateOf(false)};var showImport by rememberSaveable{mutableStateOf(false)};val clipboard=LocalClipboardManager.current;ScrollColumn{Text("Ajustes avanzados",style=MaterialTheme.typography.headlineSmall);SectionCard{Text("Configuración JSON",style=MaterialTheme.typography.titleMedium);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick={showExport=true},Modifier.weight(1f)){Text("Exportar")};OutlinedButton(onClick={showImport=true},Modifier.weight(1f)){Text("Importar")}}};SectionCard{Text("Kill switch de emergencia",style=MaterialTheme.typography.titleMedium);CodeLine("adb shell \"touch /data/local/tmp/stepphantom_disable\"");CodeLine("adb shell \"rm /data/local/tmp/stepphantom_disable\"");TextButton(onClick={clipboard.setText(AnnotatedString("touch /data/local/tmp/stepphantom_disable"))}){Text("Copiar comando")}};SectionCard{Row{Text("Log de configuración",Modifier.weight(1f));TextButton(onClick={AppDiagnostics.clear()}){Text("Limpiar")}};logs.take(40).forEach{Text(it,style=MaterialTheme.typography.bodySmall)}}};if(showExport)JsonDialog("Configuración",vm.exportJson(),true,onConfirm={showExport=false},onDismiss={showExport=false});if(showImport){var err by remember{mutableStateOf(false)};JsonDialog("Importar JSON","",false,err,"Importar",{if(vm.importJson(it))showImport=false else err=true},{showImport=false})}}
@Composable fun ScrollColumn(content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp),content=content)}
@Composable fun SectionCard(content:@Composable ColumnScope.()->Unit){ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp),content=content)}}
@Composable fun WarnCard(text:String){ElevatedCard(Modifier.fillMaxWidth(),colors=CardDefaults.elevatedCardColors(containerColor=MaterialTheme.colorScheme.errorContainer)){Text(text,Modifier.padding(16.dp),color=MaterialTheme.colorScheme.onErrorContainer)}}
@Composable fun CodeLine(text:String){Surface(color=MaterialTheme.colorScheme.surfaceVariant){Text(text,Modifier.padding(8.dp),style=MaterialTheme.typography.bodySmall.copy(fontFamily=androidx.compose.ui.text.font.FontFamily.Monospace))}}
@Composable fun JsonDialog(title:String,initial:String,readOnly:Boolean,isError:Boolean=false,confirmLabel:String="Cerrar",onConfirm:(String)->Unit,onDismiss:()->Unit){var text by rememberSaveable{mutableStateOf(initial)};AlertDialog(onDismissRequest=onDismiss,confirmButton={TextButton(onClick={onConfirm(text)}){Text(confirmLabel)}},dismissButton=if(!readOnly)({TextButton(onClick=onDismiss){Text("Cancelar")}})else null,title={Text(title)},text={OutlinedTextField(value=text,onValueChange={text=it},readOnly=readOnly,isError=isError,modifier=Modifier.fillMaxWidth().heightIn(max=340.dp))})}
